# Generated by Django 3.1.4 on 2021-01-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NickName')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_withdrawal', models.BooleanField(default=False, verbose_name='is withdrawal')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is superuser')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'auth_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('personal_phone', models.CharField(max_length=20, verbose_name='Personal Phone')),
                ('is_register', models.BooleanField(default=False, verbose_name='is register')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='is cancel')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurant')),
            ],
        ),
    ]
