# Generated by Django 3.1.4 on 2021-01-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_withdrawal',
            field=models.BooleanField(default=False, verbose_name='is withdrawal'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('personal_phone', models.CharField(max_length=20, verbose_name='Personal Phone')),
                ('is_register', models.BooleanField(default=False, verbose_name='is register')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='is cancel')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurant')),
            ],
        ),
    ]
