# Generated by Django 3.1.4 on 2021-03-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSms',
            fields=[
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='휴대폰번호')),
                ('auth_number', models.IntegerField(blank=True, verbose_name='인증번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
            ],
            options={
                'db_table': 'auth_numbers',
                'ordering': ['-created_at'],
            },
        ),
    ]
