# Generated by Django 3.1.4 on 2021-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_bundleoption_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='license_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='License Number'),
        ),
    ]
