# Generated by Django 3.1.4 on 2021-03-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210227_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='final_confirmation',
            field=models.BooleanField(default=False, verbose_name='final confirmation'),
        ),
    ]
