# Generated by Django 3.1.4 on 2021-03-01 08:29

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210301_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='reason',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='address_detail',
            field=models.CharField(default='', max_length=255, verbose_name='주소(상세)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='address',
            field=models.CharField(max_length=255, verbose_name='주소(행정)'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='business_name',
            field=models.CharField(max_length=25, verbose_name='사업주 명'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='business_phone',
            field=models.CharField(max_length=20, verbose_name='사업자 휴대폰 번호'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='delivery',
            field=models.IntegerField(choices=[(0, '배달만 가능'), (1, '배달 + 테이크아웃 가능')], verbose_name='배달 가능 여부'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='개인정보 수집 동의'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='leaflet',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.get_leaflet_path, verbose_name='전단지 등록'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='license_copy',
            field=models.ImageField(upload_to=app.models.get_license_copy_path, verbose_name='사업자등록증 사본'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='license_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='사업자등록번호'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='report',
            field=models.ImageField(upload_to=app.models.get_business_report_path, verbose_name='영업신고증 사본'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='restaurant_name',
            field=models.CharField(max_length=25, verbose_name='음식점 이름'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='restaurant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='음식점 전화번호'),
        ),
    ]
